# Generated by go2rpm 1.8.2
%bcond_with check
%global debug_package %{nil}

# https://github.com/go-co-op/gocron
%global goipath         github.com/go-co-op/gocron
Version:                1.18.0

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another pacage,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f

%global common_description %{expand:
Easy and fluent Go cron scheduling. This is a fork from
https://github.com/jasonlvhit/gocron.}

%global golicenses      LICENSE
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md README.md\\\
                        SECURITY.md

Name:           %{goname}
Release:        %autorelease
Summary:        Easy and fluent Go cron scheduling. This is a fork from https://github.com/jasonlvhit/gocron

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
